### ISSUE TITLE
[Question] Is it alternative for Universal Bypass (i.e Crowd Bypass)?

### ISSUE THREAD

**Issue by Cyberavater** [amitsingh-007/bypass-links#924]
Hi, I was looking for a link bypass solution Alternative to [Universal Bypass](https://github.com/Sainan/Universal-Bypass) (Crowd Bypass) and found this project (since UB is [dead](https://github.com/Sainan/Universal-Bypass/issues/1951)). 

Does it support Crowd Bypass? If yes, my search might've reached a destination. I'd start using it and report issues here. Thanks for your time.

**Comment by amitsingh-007** [comment]
Thanks for checking out. This is not in any way an alternative to Universal Bypass. This is just a project we are working on for the hackathon and enterprise purposes. I am really sorry if the repo's name is misleading, but at the start of the project, it was created to bypass many sites but its purpose has since been changed over time for enterprise and our needs.

PS: I am also looking for an open-source crowd bypass alternative to the Universal Bypass.
